### ISSUE TITLE
Pokemon Randomly Faint Before Picking A Move

### ISSUE THREAD

**Issue by wisejustin** [roukaour/pokecrystal#100]
its happened with 1 trainer and bugsy so far and if i out-speed with a move it instantly dies.
![20161222_002631 1](https://cloud.githubusercontent.com/assets/17464622/21416136/274d2780-c7c5-11e6-87dc-caecdec61cbf.jpg)

**Comment by roukaour** [comment]
This no longer happens. (Possibly related to #103.)
