### ISSUE TITLE
Using thunderpunch on Chinchou crashes game

### ISSUE THREAD

**Issue by njdeliberto** [roukaour/pokecrystal#101]
Assuming it's because of Chinchou's ability, but the game crashes when fighting fisherman Ralph on route 32

**Comment by FredrIQ** [comment]
Is this fixed with the type matchup+ability immunity fixes?

**Comment by njdeliberto** [comment]
Not sure, I stopped playing the compiled code a while ago. I may compile it
again for fun in the near future. Really looking forward to its release,
looks incredible!

**Comment by njdeliberto** [comment]
Ok so I am working my way back to route 32 but along the way I am noticing the type matchups aren't working. I used aerial ace on a caterpie and it hits for neutral damage. Have you noticed this? It happens no matter how many times I compile the code (thunderpunch on water pkm isnt super effective either. It's not one specific type)

**Comment by FredrIQ** [comment]
OK, so I guess I broke type matchups again...

Have you seen any SE/NVE moves at all?

**Comment by njdeliberto** [comment]
No SE/NVE moves, everything hits for neutral damage.

**Comment by njdeliberto** [comment]
Good thing is, thunderpunch on chinchou activates its ability so the original issue is fixed!

**Comment by FredrIQ** [comment]
Thanks for noticing that, means that type matchup logic is clearly running, allbeit either it's broken, or the matchup text logic broke in my refactor.
