### ISSUE TITLE
Bugsy's scyther appears in battle with 0 HP

### ISSUE THREAD

**Issue by njdeliberto** [roukaour/pokecrystal#102]
When she switches to scyther it has 0 HP

**Comment by ruvaldak** [comment]
Can't replicate. Ran through on the most recent compile and scyther switched in with full hp

**Comment by FredrIQ** [comment]
There has been several battle engine bugs concerning things like this that was fixed only somewhat recently. Try the latest build.

Also I think Bugsy is a he.

**Comment by njdeliberto** [comment]
lol really? I always thought Bugsy was a girl. Latest build works. Heck of
a game, keep it up!
