### ISSUE TITLE
randomly feinting during battle

### ISSUE THREAD

**Issue by wisejustin** [roukaour/pokecrystal#103]
i have a lvl 10 cyndaquil and every time i use ember on a wild pidgey i kill it then lose all my health and die, i also died to my rival using ember

**Comment by wisejustin** [comment]
also, now happening with other starters with their elemental moves, IE watergun now is making my starter die

**Comment by hbdfreitas** [comment]
The same happened to me. Gonna try to catch some wild Pokémon and see if it is related to STAB.

**Comment by hbdfreitas** [comment]
Ok, just did a few tests:

Replicated the bug using Razor Leaf with Chikorita. What happens is:
Independent of the target, the move always KOs the target and the user. Happened even when I used it against full health Zubats and Spinaraks, which should take only 1/4 of the damage.

Caught a Rattata to check if it had anything to do with STAB used by the player in general. It worked as usual, no bugs.

Caught a Poliwag to check if it had anything to do with former Special STABs. Couldn't replicate the bug again.

Next step: I'll start with Totodile and see if I can replicate the bug using Poliwag.

**Comment by roukaour** [comment]
This no longer happens.
