### ISSUE TITLE
trainers walks to you after battle is over

### ISSUE THREAD

**Issue by Ocarinaoftime06** [roukaour/pokecrystal#114]

**Comment by roukaour** [comment]
I can't fix this without knowing which trainer you're talking about. Do you mean that the battle happens, and *then* the trainer walks to you? Or they walk to you and start a battle as usual, and then somehow walk to you again? Also, if you're referring to a Pokémon Breeder battling you again, that's normal behavior.

**Comment by Ocarinaoftime06** [comment]
first, I walk in front of a trainer from a distance, he/she comments before battling, then right after I won the battle, he/she comes to me
