### ISSUE TITLE
first elite four trainer member gate close before you can battle him

### ISSUE THREAD

**Issue by Ocarinaoftime06** [roukaour/pokecrystal#115]

**Comment by Ocarinaoftime06** [comment]
when I walk into the first elite four room (will), the gate closes right before I can battle him. the gate suppose to close right after I pass it, but it dont. however, I am able to walk in and out the room and go back down stairs to the pokemart/center.

**Comment by Ocarinaoftime06** [comment]
but im plying the 2.2.0 version (not the faithful version)

**Comment by roukaour** [comment]
Yeah, I'm pretty sure your ROM is corrupt. No other players have had these issues with 2.2.0. Here's a pre-patched ROM to you can restart with, see if the bugs still occur: https://dl.dropboxusercontent.com/u/24474628/polishedcrystal-2.2.0.gbc

**Comment by Ocarinaoftime06** [comment]
thanks. but hey. will you tell me when the 3.0.0 update will come out?
