### ISSUE TITLE
overworld npc sprites somehow appear on screen during battle

### ISSUE THREAD

**Issue by Ocarinaoftime06** [roukaour/pokecrystal#116]

**Comment by roukaour** [comment]
Again, which battle, what sprite, how soon did they appear, etc?

Thank you for reporting these, I want to get them fixed, but I haven't encountered these bugs before and need to know just how they happen to fix them.

**Comment by Ocarinaoftime06** [comment]
trainer battles, (no gym trainers),any sprite, and I think they started to appear when I got my 6th or 7th badge.

also, no problem. im just trying to make the next update/patch better than the last. love the hack :)
