### ISSUE TITLE
Crashed when I loaded

### ISSUE THREAD

**Issue by Haxxorous** [roukaour/pokecrystal#118]
I ran the game and it took me to a screen where it shows unknowns and it says report this crash to Rangi. 
![pokemon polished crystal 2 2](https://cloud.githubusercontent.com/assets/24985023/21747850/030944cc-d52a-11e6-90c1-cb3dcad44c4d.png)

**Comment by roukaour** [comment]
Did you compile the latest code? What emulator are you using? Is "a screen where it shows unknowns" the intro animation, before the title screen? It's not happening for me in VBA 1.8.0b3.

**Comment by Haxxorous** [comment]
I have Vba i will update the vba emulator and yea before the title screen and wdym by compile the latest code

**Comment by roukaour** [comment]
Are you playing 2.2.0, or did you download the code from GitHub and type "make" to create your own ROM?

**Comment by roukaour** [comment]
Cannot reproduce.
