### ISSUE TITLE
Stat changes and natures

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#12]
Wouldn't it be better to use CheckNatureChange (in move_mon.asm) to figure out where to print the arrows rather than a lookup table-ish thing? (One would need to change it to use b instead of a since it is in a different bank, but then you can get the information on what stats increases, decreases or stay neutral)

It would be slower (since you'd need to call it one time per stat, e.g. 5 times, and it will check nature on its own each time), but I highly doubt this has a notable impact.

**Comment by roukaour** [comment]
It's more efficient and probably ends up taking less space to precalculate the arrow positions in a lookup table, instead of figuring them out each time. It would take 5 divisions and 5 modulo operations every time you check stats.

**Comment by FredrIQ** [comment]
Fair enough.
