### ISSUE TITLE
Crash when battling Schoolgirl Faith's Victreebel (Route 15)

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#121]
VBA 1.8.0b3 alerts "Unknown opcode db at cf6e" and crashes.

This is not due to its nickname (Audrey); making her a normal trainer has the same issue.

Edit: Giving all her Pokémon a simple moveset (Tackle, Leer, Vine Whip, Defense Curl) avoids the crash. Her Victreebel's moveset at level 59 would be Razor Leaf, Poison Jab, Body Slam, and Swords Dance; however, this is the same moveset as her Bellsprout and Weepinbell, which did not crash.

**Comment by FredrIQ** [comment]
I'm having issues that are probably related -- I tweaked Lyra's 1st Pokémon to be level 10 (for debugging purposes). The game immediately crashed on loading the battle if Chikorita was the one and enemy HP flashed to 0 if it was Cyndaquil/Totodile.

**Comment by FredrIQ** [comment]
My issue is related to CheckPinch (bug was introduced with b44621ed157e60c03d3aac5557bea8b7a8a35540 but CheckPinch is my stuff)

This doesn't explain Victreebel (who has Chlorophyll) so I'll look into this too once I fix whatever is wrong with CheckPinch.

**Comment by FredrIQ** [comment]
Fixed a HP-to-zero bug regarding pinch abilities that has been added to my last PR. Note that Forewarn/Anticipation still isn't tested properly so it isn't ready yet. Also noticed that this commit -- b1e3528453e5b48a8b87fd803b2aed2349b16e13 -- introduced a crash bug which might potentially be what you were seeing (not sure considering Weepinbel had the same moveset and types). The commit itself is valid, so it is exposing something else that is problematic.

**Comment by roukaour** [comment]
The rival's Magnezone in Mt. Moon also crashes when it's sent out.
