### ISSUE TITLE
Suggestion: Running "Animation"

### ISSUE THREAD

**Issue by ruvaldak** [roukaour/pokecrystal#124]
It'd be cool to have the character walking animation speed up, or double in speed, when holding B (running). It'd give a bit better indication that the player is, indeed, running. And eye candy. Nostalgic eye candy. Not particularly an animation, but it feels more like your character is running versus taking REALLY long steps

**Comment by FredrIQ** [comment]
This is something I've noticed and been slightly annoyed at myself (but not enough to ask about it). Not sure how hard it would be to address.

**Comment by roukaour** [comment]
I doubt it would take many lines of code to add, but I also don't know where to add whatever lines are necessary.

**Comment by roukaour** [comment]
Added to #123 goals for 4.0.
