### ISSUE TITLE
Pomeg/etc with no proper EV system

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#126]
Wouldn't it make more sense to have the HP restoration berries that confuse based on nature since there is no EVs? They were basically useless before, but actually ended up useful in VII since it restores HP by 50% (Sitrus does it by 25%), allthough from 1/4 rather than 1/2 HP?

**Comment by roukaour** [comment]
I've left the EV berries, and the Power items, in because the EV limit *might* get added in future. I'd like to see how battles play out in 3.0 first. If EVs don't get added in 4.0 (and they probably won't), those Berries and the raise-stat-at-low-HP Berries would be nice to add.
