### ISSUE TITLE
No trainer battles

### ISSUE THREAD

**Issue by ruvaldak** [roukaour/pokecrystal#132]
Playing a compiled version, trainers won't "spot" me, and when I talk to them they say their post-battle dialogue.

**Comment by roukaour** [comment]
Comment out these three lines in main.asm:

SeenByTrainerScript:: ; 0xbe675
	writepersonxy LAST_TALKED
	trainerflagaction SET_FLAG
	end ; TODO: REMOVE DEBUG!!!

**Comment by ruvaldak** [comment]
Idk, I might be doing something wrong, but I commented them out after I pulled with cygwin, then did "make", and I still can't battle trainers

http://imgur.com/a/PBCf7
