### ISSUE TITLE
Pokémon sprites when nicknaming are shiny

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#135]
After the Pokédex entry disappears, the sprite is shiny.

![](http://i.imgur.com/LuFcM9M.png)

**Comment by ruvaldak** [comment]
I noticed this as well during a quick play through of the current version

**Comment by roukaour** [comment]
...This bug somehow reversed itself. Now all the sprites are normal, even for shiny Pokémon like Red Gyarados.

**Comment by FredrIQ** [comment]
Probably just the same bug, e.g. whatever the nickname screen does, it's not grabbing the Shiny data correctly.
