### ISSUE TITLE
Blank TM on cancel

### ISSUE THREAD

**Issue by ruvaldak** [roukaour/pokecrystal#136]
Occasionally when moving the cursor over "cancel" in the TM pocket, I'll see the outlines of a TM, kind of like a TM without any color, instead of just an empty square. Not sure if that's intentional.

**Comment by ruvaldak** [comment]
Image: http://imgur.com/a/X0w0m

Sorry for it being rotated, my phone only takes landscape pictures for some reason

**Comment by ruvaldak** [comment]
Nvm looks like it took it correctly

I'd edit the last comment but I can't do that on my phone

**Comment by roukaour** [comment]
Yeah, this is by design, for now. I only reload the palette when navigating the list, not the icon tiles, because that would lag too much. I'll see about adding a special case for Cancel, as long as it isn't too slow.

**Comment by roukaour** [comment]
Okay, now the rounded corners go away for Cancel, but it's close enough without sacrificing efficiency:

![](http://i.imgur.com/TipyRNF.png)
