### ISSUE TITLE
New Game crash

### ISSUE THREAD

**Issue by davidmartos96** [roukaour/pokecrystal#140]
Hi, I just built latest repo version to check out the progress since 2.2.0 but starting a New Game just blanks the screen. I'm testing it with MyOldBoy emulator for Android.

**Comment by ruvaldak** [comment]
Highly recommended you use the John GBC. It's more accurate

**Comment by davidmartos96** [comment]
I have tried with John's emulator but crashes as well. 
With My old boy the screen stays white when the new game button is pressed. In John's it goes blue for just half a second and then loops from the start

**Comment by roukaour** [comment]
BGB and VBA on Windows, and VGBAnext on Android, all work for me.
