### ISSUE TITLE
Misplaced Pokedex in Mr. Pokemon's House

### ISSUE THREAD

**Issue by MadoKage** [roukaour/pokecrystal#141]
Its just a tile above the spot it was suppose to be on

**Comment by ruvaldak** [comment]
I actually noticed this as well, but I wasn't too sure if it was an "issue" or intentional

**Comment by ruvaldak** [comment]
I mean, Oak reaching across a tile twice his height in length is a little weird, but I mean, whatever

**Comment by MadoKage** [comment]
I know its rather minor, so its just here as a notice

**Comment by roukaour** [comment]
There's really no perfect option here. The sprite is designed to fit onto Prof. Oak's lab desk. In Mr. Pokémon's house, either it will hang off the edge or it will be far away. I may just remove it.

![](http://i.imgur.com/ZD749nx.png)

**Comment by MadoKage** [comment]
there's no need to remove it really it doesn't actually bug me that much

**Comment by roukaour** [comment]
Do you think it would look weird if the Pokédex stepped down towards Oak, and then disappeared?

**Comment by MadoKage** [comment]
If Oak is facing towards the pokedex it will give a impression that hes sliding it down, so I don't think it will be that odd
