### ISSUE TITLE
Running from Shadow Tag crashes game

### ISSUE THREAD

**Issue by njdeliberto** [roukaour/pokecrystal#148]
Fixed the crash, must have been my build - but now the first thing happens.

**Comment by njdeliberto** [comment]
The first thing meaning: every Pokémon uses struggle or a status move; won't attack with their damaging moveset

**Comment by FredrIQ** [comment]
Hardy - known, it's because the wildmon initialization doesn't account for the new pokémon data structure

I'll look into the other 2.

**Comment by roukaour** [comment]
Shadow Tag does not crash for me, but also no failure message is printed.

For Arena Trap, no message is printed; and for Magnet Pull, it does not work. (My Magneton ran away from a wild one with Magnet Pull.)
