### ISSUE TITLE
Make sure these original battle engine bugs are all fixed

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#158]
https://www.youtube.com/watch?v=rGqu3d3pdok

**Comment by FredrIQ** [comment]
Belly Drum -- already fixed
Love Ball -- already fixed
Present -- already fixed
Moon Ball -- already fixed
Nightmare -- was fixed, but no longer applicable
Status problems in capture -- already fixed
Thick Club/etc -- already fixed, also no longer applicable in damage calc rework if that is pushed before 3.0
Fast Ball -- already fixed
