### ISSUE TITLE
Can't use last HM in bag

### ISSUE THREAD

**Issue by njdeliberto** [roukaour/pokecrystal#159]
When I first got whirlpool I couldn't use it; now that I have waterfall I can teach whirlpool but clicking on HM6 exits the bag back to the start menu

**Comment by roukaour** [comment]
Are you using the latest code? This doesn't happen for me in BGB or VBA.

**Comment by njdeliberto** [comment]
I compiled EOD march 23rd, so maybe this has been fixed. I'll compile again in a couple days to see if it persists
