### ISSUE TITLE
Turn order has Speed-related issues

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#164]
[For example](https://www.reddit.com/r/PokemonROMhacks/comments/5xa4z7/unsure_how_to_compile_polished_crystal_with/dfg46tx/): "My Celebi was outspeeding Blue's Exeggutor until I used Dragon Dance via Metronome. This should have increased my speed but the next turn I went after he did."

**Comment by FredrIQ** [comment]
Last PR fixes that bug in particular, but doesn't mess with paralysis. Not sure if there is a bug with that, I'll look into it
