### ISSUE TITLE
Pickup table

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#20]
Regular table: For each 10 level (1-10, 11-20, etc), go to the next row. Once done with that part, the item listed has 30%, item+1 to item+6 10%, item+7 and item+8 4%. The other 2%, see the below table
* Potion
* Antidote
* Super Potion
* Great Ball
* Repel
* Escape Rope
* Full Heal
* Hyper Potion
* Ultra Ball
* Revive
* Rare Candy
* Silver Leaf
* Gold Leaf
* Full Restore
* Max Revive
* PP Up
* Max Elixir
* EXP Share

1% list: Choose randomly between Item and Item+1 after starting based on level like above
* Hyper Potion
* Nugget
* Kings Rock
* Full Restore
* Ether
* Lucky Egg
* Max Ether
* Lucky Egg
* Elixir
* Lucky Egg
* Leftovers

The algoritm is the same as in Emerald and later, but are the items reasonable or do you have other preferences? Compare with http://bulbapedia.bulbagarden.net/wiki/Pickup

**Comment by roukaour** [comment]
That looks great. Good choice to include the Silver and Gold Leaves. The rare items can be revised after more held items are added (when TMs become a bit array) (I'm working on that, it'll be in a third branch that breaks saves).
