### ISSUE TITLE
A subtle but major battle engine bug

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#27]
There is currently a bug where if a status move targetting the opponent fails at any point, every status move that targets the opponent ceases to work until the end of the battle.

Noting it here to not forget it...

Potentially trivially solved by resetting AttackMissed/FailedMessage, but I need to investigate how it got screwed up in the first place.

**Comment by roukaour** [comment]
Someone mentioned a wild Pikachu's Thunder Wave failing against their Machop in 2.2.0; this could have been the cause.

**Comment by FredrIQ** [comment]
So you are saying that this wasn't caused by abilities at all but possibly already existed before? Good to know. I'll do a bisection later and investigate when exactly it was introduced, should be easy to fix as a result.
