### ISSUE TITLE
Trainer DVs and Hidden Abilities

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#30]
The way those are set up leave pretty much every trainer having Hidden Abilities. While the feature itself is nice, the default trainers should probably have non-identical Spe/Spc to avoid this. I saw a Vulpix with Drought while playtesting things, heh.

**Comment by roukaour** [comment]
True. At some point before the 3.0 release I'll give some trainers custom DVs for better abilities (not just bosses, also on routes).

**Comment by FredrIQ** [comment]
With the structure changes, this issue in its current form is no longer relevant.
