### ISSUE TITLE
Thief causes desyncs

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#32]
While truthfully I haven't tested this outright, the very first thing Thief does is prevent the steal of player items. Why? This is a bit silly IMO, and also causes desync issues (as mentioned).

If the issue is losing items to enemy Pokémon, a fix to that is to recover items stolen after battle for Trainer battles, as is already done with the Trainer House, Battle Tower, etc.

**Comment by roukaour** [comment]
Wait, really? I looked for a routine that saved and restored held items early in the project, but didn't find one. I *did* see that Thief checked if it was in a link battle, so I assumed Nintendo's solution to players losing important items was to disable theft entirely during such battles. It still checks wLinkMode and wBattleMode, so item theft in link battles should still be impossible. Are there reported desync issues?

**Comment by FredrIQ** [comment]
According to what I read, link mode doesn't actually disable item stealing at all (all it does is skipping a check which should be redundant anyway for link mode -- checking wild mons). This is also consistent with Bulbapedia's information on the matter. What happens is that the item stealing works fine, but items are returned after the battle.
I can't actually find the exact means for how items are returned, but I'll investigate further.
