### ISSUE TITLE
Freeze during some battles

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#36]
After the last pull request, some battles freeze. I don't see a pattern in it yet.

* Guitarist Vincent in Vermilion Gym (Mewtwo/Pressure vs. second Pokémon, Magnemite)
* Juggler Horton in Vermilion Gym (Mewtwo/Pressure vs. second Pokémon, Electrode)
* Red (Mewtwo/Pressure vs. third Pokémon, Snorlax)
* Yellow (Mew/Synchronize vs. first Pokémon, Rattata)

~~One thing I noticed is that it seems related to match duration. Against Vincent and Horton, when I knocked out their first Pokémon and continued battling with Mewtwo, it would freeze, but when I switched to Mew I could knock them out on the first turn and end the battle.~~ My very first attack against Yellow's Rattata froze.

I'll update this with more thorough testing later.

**Comment by FredrIQ** [comment]
Abilities for reference:
Magnemite: Analytic
Electrode: Static
Snorlax: Immunity
Rattata: Hustle

2 of those are related to damage calculations and are coded in the same place, so there is probably something going awry there. Not sure with the others.

**Comment by roukaour** [comment]
Battling a wild Sentret with Mewtwo/Pressure: my Nasty Plots work, then Psystrike softlocks with music still playing. On the other hand, I was able to Psystrike wild Tentacool. Rapidash, Tangela, Golbat, and Onix, and multiple Bellsprout owned by the same trainer.

Psystrike KOs Sailor Eugene's Poliwhirl, but both Psystrike and Nasty Plot softlock against his second Pokémon, a Raticate.

Against Super Nerd Teru, I can Psystrike his first Magnemite and Voltorb, but against his second Magnemite it softlocks. They must have the same ability, since trainers have common DVs...

**Comment by FredrIQ** [comment]
So probably not tied to abilities directly then. I'll investigate later today, I think I know where the issue is (but not the exact problem).

**Comment by FredrIQ** [comment]
I'm having some trouble consistently reproducing this making debugging a pain. Do you have a save that can do it 100% of the time? If so, would you mind sharing it?

**Comment by roukaour** [comment]
I've encountered 10 Rattata here and every time I use Psystrike it freezes. (It doesn't freeze against Hoothoot.) Here's the save file, and a VBA-M quicksave against a Rattata.

* [mewtwo-vs-rattata.sav](https://dl.dropboxusercontent.com/u/24474628/mewtwo-vs-rattata.sav)
* [mewtwo-vs-rattata.sgm](https://dl.dropboxusercontent.com/u/24474628/mewtwo-vs-rattata.sgm)

**Comment by FredrIQ** [comment]
Fixed it, thanks.

The reason it was sporadic was that a function I was using was making use of a secondary parameter I overlooked -- IsInArray checks de for how many bytes to advance when checking, and since I never set de, it ended up advancing by whatever de happened to contain on the last call, hence the "randomness".
