### ISSUE TITLE
RunActivationAbilities is called before the ability is updated

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#40]
For the first rival battle, Sentret's Frisk activates, then activates again when his starter is sent out. The same thing happens with other abilities controlled by RunActivationAbilities, such as Pressure.

**Comment by FredrIQ** [comment]
That is strange considering I always (or should always) run it after Spikes damage. It is possible that I forgot to actually update the ability in a certain switch-out logic, but this seems unlikely, more likely is that I screwed up the order of routine calls somewhere. I'll look into it.

**Comment by FredrIQ** [comment]
Found out the issue -- NewEnemyMonStatus can be called before the Pokémon is switched, which is the case when a pokémon faints. I'll investigate if this happens on other switches too, because then I need to revise where I update ability.
