### ISSUE TITLE
`farcall GetAbility' crashes in DoPoisonStep

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#43]
Message in VBA: "Unknown opcode fc". Commented out for now.

**Comment by FredrIQ** [comment]
That particular error makes no sense to me. I'll look into it, but farcall is unneeded since GetAbility was moved to home.asm. Perhaps simply using call works.

**Comment by roukaour** [comment]
...Huh, "call" does work. I thought there were other places where an unnecessary "farcall" was harmlessly used. Anyway, fixed.
