### ISSUE TITLE
Gift pokemon HP quirk

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#44]
My starting Cyndaquil had 19/20HP. Possibly the old method of HP DV calculation is used somewhere?

EDIT. I assume that the fact that Lyra started with a shiny Chkiorita is a bug? It also started with less than max HP

**Comment by roukaour** [comment]
Yes, those are both bugs that I'm looking into. The HP one is more apparent with higher levels: some Pokémon have less than max, some have more. Same goes for trainers' Pokémon, which have weird stats and are sometimes shiny. Wild Pokémon look correct, though.

**Comment by roukaour** [comment]
Fixed.
