### ISSUE TITLE
Pokémon are still not given the correct data

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#46]
Stats:
According to http://www.psypokes.com/gsc/dv.php a Totodile can't have 18HP, 10atk, 11defense, 8speed, 9SpA, 9SpD (HP, attack and speed is lower than the minimum). This was calculated disregarding the nature (Lonely: actual Attack was 11 and defense 9, but even if therer is something wrong with the nature calculation, Speed is still off -- and the nature calc worked fine before when I checked during implementation of them) I'm not referring to DVs not matching what it expects -- that makes sense since the DVs were split, but the HP is far lower than it should be, and Attack and Speed were also a bit lower.

PPs:
This should be easier to track down -- my Totodile started with 40/35 pp for Scratch and 15/30 for Leer.

EDIT: http://www.psypokes.com/dex/iv.php is easier to use when factoring in Nature, but has a small chance of the upper limit being off by 1 for when 31 IVs increase something by 1 compared to 30, which is equavilent to 15DVs

**Comment by roukaour** [comment]
The PP issue was a simple fix. hl was being shifted by GetRandomGender.

Whatever the stats issue was might also have been fixed. For example, my Hardy Totodile has HP/Atk/Def/Spd/SAt/SDf 21/11/12/10/9/11. Its Attack, Defense, and Speed are all within valid ranges. Its Special Attack and Defense don't match because they have different DVs now, but they're both within the individual valid ranges. Same goes for HP. Trying with a few other starters also works.

**Comment by FredrIQ** [comment]
I re-rolled and got this:

Stats shown (Possible true stat range)
HP: 22 (20-21)
Atk: 13v (9-11)
Def: 13^ (12-13)
SpA: 11 (9-10)
SpD: 12 (9-11)
Spe: 9 (9-10)

This time the stats are too high.

**Comment by roukaour** [comment]
Hmm. Try raising the starter level to 100, any discrepancies will be easier to see.

Here's my level 100 Adamant Cyndaquil as an example:

HP: 188 (188–218)
Atk↑: 131 [131 / 110% = 119] (109−139)
Def: 111 (91–121)
Spd: 159 (135–165)
SpA↓: 133 [133 / 90% = 148] (125–155)
SpD: 129 (105–135)

I'm going to try hard-coding min/max DVs and a neutral nature and see what kind of stats it gives.

**Comment by FredrIQ** [comment]
131 is also invalid.

119*11=1309
1309/10=130

**Comment by roukaour** [comment]
Okay, this is interesting: the nature multiplier isn't being applied. A level 100 min-DV Adamant Cyndaquil has the exact same stats as a Quirky one.

**Comment by FredrIQ** [comment]
I see the issue, the nature byte is loaded but there is no & NATURE_MASK performed.

Allthough this isn't the only issue or HP wouldn't screw up.

**Comment by roukaour** [comment]
Committed that while I was editing it. :P I think there's another issue: "ld bc, MON_NATURE - MON_DVS" makes c no longer store the stat being calculated, which GetNatureStatMultiplier needs. "pop bc; push bc" should fix that if so. Will pull your commit and test.

**Comment by FredrIQ** [comment]
So basically, move GetNatureStatMultiplier after pop bc+hl?
