### ISSUE TITLE
Potential typo for EV granting items (vitamins)?

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#48]
You apparently effectively removed the limit on how far vitamins can go, which is nice. However, you do a check on 242 and block if it's >=242. Surely you meant to check >242 (or rather, >=243)? Also, perhaps allow it up to 252, but only boost to 252 in that case? I was going to fix this myself, but wasn't sure if it was intentional or not so I just wanted to check.

Relevant code: item_effects.asm:1404

**Comment by roukaour** [comment]
Yes, it should check >242, so a vitamin can only take you up to 252. I didn't add a case to give less than 10 EVs because that would be less benefit for the $9800 cost.

**Comment by FredrIQ** [comment]
To me, it wouldn't really be an issue (if I am using vitamins that excessively, I probably don't have money issues and just want to max it), however I'll just keep it at that then.
