### ISSUE TITLE
TM marts are buggy

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#54]
* The displayed TM name and description are off by one (too low). The TM you receive is correct.
* ~~The code that's supposed to check if you already own a TM causes the save dialog to appear.~~

**Comment by FredrIQ** [comment]
The latter sounds like a farcall vs call issue.

**Comment by roukaour** [comment]
I had tried replacing "call CheckTMHM" with farcall, and it *does* work, but I want to understand why before committing it—RecieveTMHM and ReceiveItem are defined right alongside it and work with regular calls.

**Comment by FredrIQ** [comment]
Are you positive that it works and it isn't just "luck" with undefined behaviour just happening to align properly?

**Comment by roukaour** [comment]
It could easily be "luck", since I don't see a reason why it *should* be a farcall. For now I'm taking a break from it and doing other features. Is there a convenient way to see which bank a given label ended up in?

**Comment by FredrIQ** [comment]
See the symbol file.

[1521][fiq@fiq-desktop ~/pokecrystal]$ LANG=C grep -r "StartHail" *
(...)
polishedcrystal-2.2.0.sym:0D:7772 BattleCommand_StartHail

0D there is bank

**Comment by FredrIQ** [comment]
OK, I see the issue, kind of.

I don't know exactly what happens, but I know why -- there are 2 functions named CheckTMHM. Rename one of them.

I had similar weird nonsensical bugs when I had a RAM address and a function named the same.

**Comment by roukaour** [comment]
Thank you.

> there are 2 functions named CheckTMHM

Sigh. Assembly really makes me appreciate how convenient C is: quantity-checked function parameters (let alone type-checking), scope-unique identifier names, unlimited local variables that the compiler fits into registers...

Then again, working on pokecrystal in 2016, with its macros and quick edit-build-test cycle and HD computer screens, is still easier than what I expect Gamefreak was doing in the 90s.
