### ISSUE TITLE
odd gfx.py-related error

### ISSUE THREAD

**Issue by FredrIQ** [roukaour/pokecrystal#6]
Hi.
There seems to be an issue regarding gfx.py. I solved this in my own fork of this by replacing gfx.py with an ordinary file retaining its content. Otherwise, this happens (Branch upstream was a branch I created based on upstream to more easily be able to select a specific commit to potentially send a PR about):

[584][fiq@fiq-desktop ~/pokecrystal]$ LANG=C git checkout upstream
error: unable to create symlink gfx.py: File name too long
D       gfx.py
Switched to branch 'upstream'
Your branch is up-to-date with 'origin/upstream'.

This is how I solved the issue: https://github.com/FredrIQ/pokecrystal/commit/dfde55f8240a0f545c1551bdde269f5c51eb5e9b

**Comment by roukaour** [comment]
Hmm. I deleted the file and made a new one with the same content. Is there still a problem?

**Comment by FredrIQ** [comment]
That fixed it. Thanks!
