### ISSUE TITLE
All moves crash in battle

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#63]
Any move that I use immediately crashes. (Tested: Nasty Plot, Barrier, Mist, Psystrike, Hurricane, Future Sight, Tackle.)

If I switch Pokémon, the foe successfully uses their move, but then it crashes.

**Comment by FredrIQ** [comment]
Uh-oh, sorry. Probably caused by a subtle change overlooked after testing.

I'll look into it.
