### ISSUE TITLE
Every wild Pokémon has a Hardy nature

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#70]
Noticed while attempting to replace this code in engine/move_mon.asm:

    	cp HARDY
    	jr z, .neutral
    	cp DOCILE
    	jr z, .neutral
    	cp SERIOUS
    	jr z, .neutral
    	cp BASHFUL
    	jr z, .neutral
    	cp QUIRKY
    	jr z, .neutral

with this:

    .check_neutral
    	and a
    	jr z, .neutral
    	sub 6
    	jr nc, .check_neutral
    	ld a, b

**Comment by FredrIQ** [comment]
Hardy is 0, that should make the problem obvious. IIRC there is a todo comment on LoadEnemyMon on creating proper personality data for wild mons.

**Comment by roukaour** [comment]
> IIRC there is a todo comment on LoadEnemyMon on creating proper personality data for wild mons. I can look into it.

Oh, of course. Most of the generated personality data is incomplete, like shininess. I'll get to it eventually.

> Personally I don't see the need to optimize GetNatureStatMultiplier, but rather than loop twice, you can just add a neutrality check in .penalty.

Aesthetics, basically. :/ Not going to play code golf with everything, but this was a simple enough edit. And thanks for the improvement.

**Comment by wisejustin** [comment]
bred mons and all wild mons are all hardy natured still. i dont know if you've worked on it or not. just thought id comment on this.
