### ISSUE TITLE
A Traced ability activates twice

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#77]
When Porygon Traced my Mewtwo's Pressure, it printed Pressure's message twice. (And it said "Porygon traced OPABIL", but that's just not implemented yet, not a bug.)

**Comment by FredrIQ** [comment]
OPABIL was when I was going to add a way to always point to ability buffers. I settled on not doing that in the end (see ShowAbilityActivation) but just forgot to change the Trace message. In any case, the PR above should address both issues.
