### ISSUE TITLE
Generating pngs of maps and tilesets

### ISSUE THREAD

**Issue by krruzic** [roukaour/pokecrystal#79]
Sorry if this is the wrong place to ask, but I tried a bunch of stuff on my own and couldn't get it to work. With `utils/map.py` I'm getting `No such file or directory 'tilesets/10_metatiles_colored.png'` when I set tilesetID to 10. I also don't know what the tilesetID is supposed to be (or what height is? I'm guessing # of tiles in a column). Anyway, there are no pngs in the repo aside from screenshots which makes me wonder if using these utilities is even possible. I also tried the tools in the pokemontools submodule and they error out about missing files.

A more general question would be: how can I set up an environment to work on this? I'm thinking of making my own romhack based off this but if I can't even edit/view maps that would be difficult.

**Comment by roukaour** [comment]
Hi! First of all, make sure you've recursively checked out the pokemontools submodule; it should be in the extras directory. I assume you can build the ROM itself, so you have Python 2 working. That's all that's needed for environment setup.

Say you want a map of Azalea Town. constants/map_constants.asm has the height—`mapgroup AZALEA_TOWN, 9, 20`—and maps/map_headers.asm has the tileset—`map_header AzaleaTown, TILESET_JOHTO_2`, which according to constants/tilemap_constants.asm is tileset 02. So you run a command like this:

    utils/map.py maps/AzaleaTown.blk 9 02

This should generate maps/AzaleaTown.png. As a side effect, it runs `utils/metatiles.py 02`, which generates gfx/tilesets/02.png and tilesets/02_metatiles.png.

It sounds like your problem *might* be that the utils/metatiles.py subcommand isn't running. I do it my calling `os.system` in Python. It works for me, but you can try debugging it.

**Comment by krruzic** [comment]
Yeah, I can build the ROM fine. Found out I was missing some traceback, it's failing [here](https://github.com/pret/pokemon-reverse-engineering-tools/blob/master/pokemontools/wram.py#L179). `const_value` isn't being added to the constants dict for some reason and I can't find where it's supposed to be added in the first place. I'm going to try hard coding it for now as I debug more.

Full traceback in case anyone has a similar problem: 


```
Traceback (most recent call last):
  File "gfx.py", line 8, in <module>
    from extras.pokemontools import gfx, lz
  File "/home/krruzic/pokecrystal/extras/pokemontools/__init__.py", line 2, in <module>
    import crystal
  File "/home/krruzic/pokecrystal/extras/pokemontools/crystal.py", line 1456, in <module>
    event_flags = wram.read_constants(os.path.join(conf.path, 'constants/event_flags.asm'))
  File "/home/krruzic/pokecrystal/extras/pokemontools/wram.py", line 210, in read_constants
    return scrape_constants(lines)
  File "/home/krruzic/pokecrystal/extras/pokemontools/wram.py", line 197, in scrape_constants
    bss.read_bss_sections(text)
  File "/home/krruzic/pokecrystal/extras/pokemontools/wram.py", line 176, in read_bss_sections
    self.constants[name] = eval(value, self.constants)
  File "<string>", line 1, in <module>
NameError: name 'const_value' is not defined
Traceback (most recent call last):
  File "utils/metatiles.py", line 209, in <module>
    main()
  File "utils/metatiles.py", line 206, in main
    process(tileset, palette_map, metatiles)
  File "utils/metatiles.py", line 157, in process
    tileset = Tileset(tileset_name, palette_map)
  File "utils/metatiles.py", line 36, in __init__
    reader = png.Reader(filename=filename)
  File "/home/krruzic/pokecrystal/utils/png.py", line 1362, in __init__
    self.file = open(kw["filename"], "rb")
IOError: [Errno 2] No such file or directory: 'gfx/tilesets/02.png'
Traceback (most recent call last):
  File "utils/map.py", line 122, in <module>
    main()
  File "utils/map.py", line 119, in main
    process(blockfile, height, metatiles)
  File "utils/map.py", line 99, in process
    metatiles = Metatiles(metatiles_name)
  File "utils/map.py", line 34, in __init__
    reader = png.Reader(filename=filename)
  File "/home/krruzic/pokecrystal/utils/png.py", line 1362, in __init__
    self.file = open(kw["filename"], "rb")
IOError: [Errno 2] No such file or directory: 'tilesets/02_metatiles_colored.png'
```

**Comment by krruzic** [comment]
Well, never mind. You were right, the subcommands aren't running, first I needed to use gfx.py in the extras package, then the metatiles.py then map.py

The traceback I posted is still a problem as it stops map_editor.py in extras from working
