### ISSUE TITLE
The rematch with Koga crashed

### ISSUE THREAD

**Issue by roukaour** [roukaour/pokecrystal#81]
Oddities noticed during battle:

* Max Elixir would have "no effect" on my Mewtwo even though Psystrike had 0/10 PP
* At one point after exiting a menu, Mewtwo's sprite glitched
* I was speeding through a battle with a Minimized Muk and the screen turned white and froze

I'll try to narrow down the cause later.

Edit: In another battle, a level 38 Dewgong outsped my level 100 Mewtwo.

**Comment by FredrIQ** [comment]
As for the other battle, does your Mewtwo have >255 speed? Maybe I forgot to account for an overflow somewhere in my speed refactor, because the code looks OK otherwise.

**Comment by roukaour** [comment]
A 120 Speed wild Arbok still outsped my 275 Speed Mewtwo.

**Comment by roukaour** [comment]
All three issues here appear fixed.
