### ISSUE TITLE
Wrong sprite on decoration consoles

### ISSUE THREAD

**Issue by mratmartinez** [roukaour/pokecrystal#82]
The game consoles for decorating your room are wrong, when you put the NES in the PC, the sprite is the SNES but it says it's the NES.
The same happens with the others:
SNES (PC) > N64 (over world)
N64 (PC) > GameCube (over world)
GameCube (PC) > Wii (over world)

**Comment by roukaour** [comment]
Thanks, that's been fixed for 3.0.
