### ISSUE TITLE
Asking Kurt to make a ball soft-locks

### ISSUE THREAD

**Issue by fraioli** [roukaour/pokecrystal#87]
Asking Kurt to make a ball results in a "No windows available for popping." dialogue and then the game soft-locks.

![screen shot 2016-11-21 at 11 40 31 am](https://cloud.githubusercontent.com/assets/2308372/20497794/6ab6d122-afdf-11e6-9bc4-736b22559c28.png)

**Comment by roukaour** [comment]
Thanks. Whatever the cause is, it's not in [event/kurt.asm](https://github.com/roukaour/pokecrystal/commits/master/event/kurt.asm); none of its few changes have altered the push or pop commands.

**Comment by roukaour** [comment]
Turns out this was caused by a new change (the separate Berry pocket in the Bag), not something in 2.2.0. I assumed players' bug reports would be based on the released version. Anyway, it's fixed now.

**Comment by fraioli** [comment]
Ah sorry, I should've mentioned I was on TOT. Trying out some of the new features. Thanks for fixing though! I'll continue to file issues as I come across them if it's helpful.
